# Generated by Django 4.2.5 on 2023-09-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoautomotive', '0003_alter_sendemail_options_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product',
        ),
    ]
