# Generated by Django 4.2.5 on 2023-09-23 09:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecoautomotive', '0004_rename_product_id_cart_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='AddCart',
        ),
    ]
