# Generated by Django 4.2.5 on 2023-09-24 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecoautomotive', '0006_accessories_quantity_addcart_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcart',
            name='accessories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecoautomotive.accessories'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternatephonenumber', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '5. Shipping Address',
                'verbose_name_plural': '5. Shipping Address',
            },
        ),
    ]
