# Generated by Django 4.2.5 on 2023-09-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoautomotive', '0007_addcart_accessories_shippingaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.TextField(),
        ),
    ]
