# Generated by Django 4.2.5 on 2023-09-26 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecoautomotive', '0008_alter_shippingaddress_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcart',
            name='accessories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecoautomotive.accessories'),
        ),
        migrations.AlterField(
            model_name='addcart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecoautomotive.products'),
        ),
    ]
