# Generated by Django 4.2.5 on 2023-10-10 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoautomotive', '0010_shippingaddress_name_billingaddress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name': '6. Billing Address', 'verbose_name_plural': '6. Billing Addresses'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name': '5. Shipping Address', 'verbose_name_plural': '5. Shipping Addresses'},
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='alternatephonenumber',
            field=models.CharField(help_text='Format: +1234567890', max_length=100),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='postal_code',
            field=models.CharField(help_text='Format: 12345', max_length=10),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='alternatephonenumber',
            field=models.CharField(help_text='Format: +1234567890', max_length=100),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.CharField(help_text='Format: 12345', max_length=10),
        ),
    ]
