# Generated by Django 4.2.5 on 2023-10-12 08:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecoautomotive', '0014_alter_billingaddress_user_alter_shippingaddress_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billingaddress',
            unique_together={('user',)},
        ),
        migrations.AlterUniqueTogether(
            name='shippingaddress',
            unique_together={('user',)},
        ),
    ]
