# Generated by Django 4.2.5 on 2023-10-14 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecoautomotive', '0015_alter_billingaddress_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=500, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=500, null=True)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('confirm', 'Confirm'), ('on_the_way', 'On the way'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('cancelled', 'Cancelled'), ('confirm', 'Confirm')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('accessories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories_details', to='ecoautomotive.accessories')),
                ('billingAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='ecoautomotive.billingaddress')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='ecoautomotive.products')),
                ('shippingAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='ecoautomotive.shippingaddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cust_name', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '7. Order',
                'verbose_name_plural': '7. Orders',
            },
        ),
    ]
