# Generated by Django 4.2.5 on 2023-10-14 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecoautomotive', '0017_rename_order_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='accessories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessories_details', to='ecoautomotive.accessories'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='ecoautomotive.products'),
        ),
    ]
