# Generated by Django 4.2.5 on 2023-10-17 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoautomotive', '0019_orders_deliverycharges_orders_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='deliverycharges',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='discount',
        ),
    ]
