# Generated by Django 4.2.5 on 2023-10-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoautomotive', '0020_remove_orders_deliverycharges_remove_orders_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='deliverycharges',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
