# Generated by Django 4.2.5 on 2023-10-17 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecoautomotive', '0025_alter_orders_deliverycharges_alter_orders_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order_trackings', to='ecoautomotive.orders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userorder_trackings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '8. OrderTracking',
                'verbose_name_plural': '8. OrdersTracking',
            },
        ),
    ]
