# Generated by Django 4.2.5 on 2023-10-17 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecoautomotive', '0029_userordertracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationScrollHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '9. Notification Scroll',
                'verbose_name_plural': '9. Notification Scroll',
            },
        ),
    ]
