# Generated by Django 4.2.5 on 2023-10-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoautomotive', '0031_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='product',
        ),
        migrations.AddField(
            model_name='orders',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_orders', to='ecoautomotive.products'),
        ),
        migrations.RemoveField(
            model_name='orders',
            name='accessories',
        ),
        migrations.AddField(
            model_name='orders',
            name='accessories',
            field=models.ManyToManyField(blank=True, null=True, related_name='accessory_orders', to='ecoautomotive.accessories'),
        ),
    ]
