# Generated by Django 4.2.5 on 2023-10-24 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecoautomotive', '0032_remove_orders_product_orders_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='products',
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_details', to='ecoautomotive.products'),
        ),
        migrations.RemoveField(
            model_name='orders',
            name='accessories',
        ),
        migrations.AddField(
            model_name='orders',
            name='accessories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accessories_details', to='ecoautomotive.accessories'),
        ),
    ]
